# Generated by Django 4.1.3 on 2023-01-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
    ]
