# Generated by Django 4.1.3 on 2023-01-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_post_category_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
    ]
