# Generated by Django 4.1.3 on 2023-01-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_remove_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
