# Generated by Django 4.1.3 on 2023-01-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_remove_post_category_post_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Product_Price',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
