# Generated by Django 4.1.5 on 2023-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tages_n',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
